### ISSUE TITLE
copy change for free provider kits

### ISSUE THREAD

**Issue by scottsnyder01** [Geneticure/geneticure.com#123]
https://github.com/Geneticure/geneticure.com/blob/2f962778c92dd4c61c17fb74d9b6db3cb007f65d/src/sections/providers/hero.astro#L22

Change to:

Register for your provider account and we'll coordinate an introduction to Geneticure and answer any questions you may have. In many cases we can also offer complimentary testing to demonstrate the value of the test.

**Comment by RobertAKARobin** [comment]
@scottsnyder01 Updated!

**Comment by scottsnyder01** [comment]
Have you been watching blaze and the monster machines? That is blazing fast.

From: "Robin (Robert) Thomas" ***@***.***>
Reply-To: "Geneticure/geneticure.com" ***@***.***>
Date: Thursday, March 23, 2023 at 7:47 PM
To: "Geneticure/geneticure.com" ***@***.***>
Cc: Scott Snyder ***@***.***>, Mention ***@***.***>
Subject: Re: [Geneticure/geneticure.com] copy change for free provider kits (Issue #123)


@scottsnyder01<https://github.com/scottsnyder01> Updated!

**Comment by RobertAKARobin** [comment]
Haha, perks of an obsessive personality.
