### ISSUE TITLE
Matt

### ISSUE THREAD

**Issue by scottsnyder01** [Geneticure/geneticure.com#28]
https://github.com/Geneticure/geneticure.com/blob/5e8a7bd18578a4af220529163f70b519890213cb/src/pages/company.astro#L1

I think it's strange to have Matt on the team page as 'internal counsel' right now - suggest removing him. He's not active in the day to day and weird to have this type of role on our website at this stage.

**Comment by RobertAKARobin** [comment]
Fine with me. Any other changes to personnel?

**Comment by RobertAKARobin** [comment]
Note that the text for everyone is here: https://github.com/Geneticure/geneticure.com/blob/main/src/text/team.ts

**Comment by scottsnyder01** [comment]
Nope everything else looks good. Sorry I couldn’t find the text, thank you

Scott Snyder
952.210.5851
________________________________

**Comment by RobertAKARobin** [comment]
No worries, takes getting used to

**Comment by RobertAKARobin** [comment]
Fixed by #29
