### ISSUE TITLE
make 'other stuff we're working on' section fonts larger

### ISSUE THREAD

**Issue by scottsnyder01** [Geneticure/geneticure.com#85]
https://github.com/Geneticure/geneticure.com/blob/ef75bc9ed2cbc181c477efaa19ae1a3f6f820f6e/src/text/news.ts#L8

![image](https://user-images.githubusercontent.com/35838118/200043895-92b3b0de-8052-46b0-8032-65f6ea44df41.png)

**Comment by RobertAKARobin** [comment]
Closed by https://github.com/Geneticure/geneticure.com/pull/86
